name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: 'nextjs/.nvmrc'

      - name: Install dependencies
        run: cd ./nextjs && npm install

      - name: Run Vitest tests
        run: cd ./nextjs && npm run test --coverage

      - name: Build NextJS
        run: cd ./nextjs && npm run build


  strapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: 'strapi/.nvmrc'

      - name: Install dependencies
        run: cd ./strapi && npm install

      - name: Build Strapi Application
        run: cd ./strapi && npm run build
