name: Pull Request Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd ./nextjs && npm install

      - name: Install dependencies
        run: cd ./strapi && npm install

      - name: Run Vitest tests
        run: cd ./nextjs && npm run test --coverage

      - name: Build NextJS
        run: cd ./nextjs && npm run build

      - name: Build Strapi Application
        run: cd ./strapi && npm run build